DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS requetes;
DROP TABLE IF EXISTS svg;

CREATE TABLE people (
  tkey INTEGER PRIMARY KEY AUTOINCREMENT,
  ID VARCHAR(20) UNIQUE NOT NULL,
  Nom TINYTEXT NOT NULL,
  Prenom TINYTEXT NOT NULL,
  Recherche MEDIUMTEXT NOT NULL,
  Date INTEGER,
  DateStr VARCHAR(4) NOT NULL
);

CREATE TABLE svg (
  tkey INTEGER PRIMARY KEY AUTOINCREMENT,
  ID VARCHAR(20) UNIQUE NOT NULL,
  svgGraph BLOB(65535),
  FOREIGN KEY (ID) REFERENCES people (ID)
);

CREATE TABLE requetes (
  tkey INTEGER PRIMARY KEY AUTOINCREMENT,
  date DATETIME NOT NULL,
  requete TINYTEXT NOT NULL
);