DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS requetes;
DROP TABLE IF EXISTS svg;

CREATE TABLE people (
  ID VARCHAR(20) PRIMARY KEY,
  Nom TINYTEXT,
  Prenom TINYTEXT,
  Recherche MEDIUMTEXT,
  Date INTEGER,
  DateStr VARCHAR(4) NOT NULL
);
CREATE INDEX Recherche ON people (Recherche); 

CREATE TABLE svg (
  ID VARCHAR(20) PRIMARY KEY,
  svgGraph BLOB(65535),
  FOREIGN KEY (ID) REFERENCES people (ID)
);

CREATE TABLE requetes (
  tkey INTEGER PRIMARY KEY AUTOINCREMENT,
  date DATETIME NOT NULL,
  requete TINYTEXT NOT NULL
);